# Config file for the CSR registers

[csrs]
csr_count = 23

csr_wmask = [
    0x00007188, # MSTATUS
    0xFFFF0888, # MIE
    0xFFFFFF01, # MTVEC
    0xFFFFFFFF, # MSCRATCH
    0xFFFFFFFE, # MEPC
    0x8000001F, # MCAUSE
    0x00000000, # MTVAL
    0x00000000, # MIP
    0x00000000, # VENDORID
    0x00000000, # MARCHID
    0x00000000, # MIMPID
    0x00000000, # MHARTID
    0x00000000, # MISA
    0x00000000, # CYCLE
    0x00000000, # CYCLEH
    0x00000000, # INSTR
    0x00000000, # INSTRH
    0x00000000, # FLUSH
    0x00000000, # FLUSHH
    0x00000000, # WAIT
    0x00000000, # WAITH
    0x00000000, # DECOD
    0x00000000, # DECODH
]
